### PR TITLE
WIP: Simplify benchmarking infrastructure

### PR DESCRIPTION
**Pull request by snowleopard**
@nobrakal I've tried to do some simplification of your benchmarking infrastructure: removed the nullary case `Consumer`, and hopefully came up with a bit clearer naming. 

What do you think?

I did some changes to the Cabal file to make it work with my Stack-based setup.

### CODE REVIEW

**Comment by nobrakal** [comment]
Well, that is super-simplifications, thank you !

Some things:
* Why removing the `Consumer` constructor ? Here for benchmarking such a function, you are creating a false argument with the function name and an empty argument, it is not very beautiful ^^, and the resulting benchmark will have a name like: 
```
isEmpty/Circuit/100/isEmpty
```
which make it difficult for making a good output. 
Moreover, you are creating a consumer with the `consumer` function, which behave like a constructor!
Making a different constructor will only imply a new line for `benchAlgorithm` and not change many thing otherwise, especially if we use helper functions (see behind)

* We can provide a "hiding constructors" (like `consumer`) function for algorithms with:
``` Haskell
notConsumer :: (GraphImpl g, Show a) => String -> (a -> g-> b) -> [a] -> Suite g
notConsumer n f args = Suite n $ Algorithm f $ withNames args
```

* Thank you for the `stack` config!

* Forcing the `base >= 4.11` in the `.cabal` make the travis-buid fail, and just for note, `criterion` is now `1.4` and it build like a charm with it.

Ps: You are better than me to find function name ^^

**Comment by snowleopard** [comment]
Thanks for the comments! For now this is just the first step of an experiment and I expect more commits.

> Why removing the `Consumer` constructor ? 

Primary to reveal the common structure and reduce the number of notions. This potentially allows further simplifications, by joining `Suite` and `Algorithm` into the same datatype. 

> Moreover, you are creating a consumer with the consumer function, which behave like a constructor!

True, in this sense I haven't yet fully removed the notion of `consumer`. I thought that at some point I'll rename it to `nullary` and add `unary` and `binary` helper functions for things like `hasEdge`, so that the user of this infrastructure library can pass `isEmpty`, `hasVertex` and `hasEdge` directly, without the need to bother with `uncurry`. I'd argue these are more common names for what you are trying to model.

> the resulting benchmark will have a name like ...

Indeed. I haven't yet looked at the resulting naming. I'm sure this can be dealt with without the need for an extra notion of 'consumers', which seem unnecessary and (at least for me) confusing. 

P.S.: I'll look into Travis failures.

**Comment by nobrakal** [comment]
That's great and a lot clearer than my code ^^ !

I am still not very fond of the "Consumer" removal. I find the `simpleSuite name algorithm = Suite name (const algorithm) (const [("", ())])` not very beautiful ^^. A `simpleSuite` is so different from other algorithms, I think it is a good idea to reflect this difference in the type.

 > Primary to reveal the common structure and reduce the number of notions.

The number of notion is here, you will have to introduce `nullary` and other helpers functions, why not introduce with it the corresponding type (like `Nullary` if you don't like `Consumer` :) ) ? We can "hide" the type by not exporting it from BenchGraph if you think this can create confusion for the end-user (`nullary` and `unary` will return only a `Suite`).

On the other side, your implementation is very simple and clean :+1:

**Comment by nobrakal** [comment]
Ok, you convinced me ! It is coherent with itself and seems to be a lot clearer. As you said, after some try, I don't think it is possible to remove the need of `["",()]` without introducing new notions (or making the code more complicated by encapsulating the `inputs` field in `Maybe` or `Either`).

I merge this (and who knows, maybe a solution will come later !)

Thank you again for the work @snowleopard  :)

**Comment by snowleopard** [comment]
Great! I'm sure we'll find further improvements :)

**Pull request merged**
